### PR TITLE
AVR: Add AVR support (tooling, core, and tests)

### PR DESCRIPTION
**Pull request by VoltagedDebunked**
**Detailed description**

Adds AVR architecture support.

* Implemented AVR disassembler backend
* Integrated with `cstool`
* Added CMake and legacy Makefile support
* Code formatted with `clang-format`

**Test plan**

Installed and built this version.
Compiled example AVR programs using my own code.
Validated disassembly output with `cstool`.

### CODE REVIEW

**Review by Rot127 — CHANGES_REQUESTED** [review]
Please revert the formatting to the non-related files.

Also, please extend `cstest` and generate the python binding constants so the tests can run.

**Comment by Rot127** [comment]
Thanks for the new module!

I am a little bit confused though how you built it. It does look like some code is from LLVM. But it is not generated by Auto-Sync. Have you worked on it by hand?

I would highly recommend to use Auto-Sync to port the module. It gives you more consistent results and can be updated more easily. Also you would get the 32bit instructions. Currently it looks like only the 16bit instructions are supported.

**Comment by VoltagedDebunked** [comment]
Alright, ill work on it. thanks for the feedback!

Yes, i have worked on it by-hand, i never really worked that much with llvm, i did use the provided modules, and autosync somewhy just didnt work, so i made it manually.

ill try doing autosync though. maybe fix it, somehow.

**Comment by Rot127** [comment]
> somewhy just didnt work, so i made it manually.

Can you please describe what the error was you ran into? If you use Python 3.13 it will be fixed with https://github.com/capstone-engine/capstone/pull/2705. Until then it is necessary to use Python 3.12 unfortunately. You can do this with an virtual environment with [uv](https://docs.astral.sh/uv/).

```
uv venv --python 3.12
uv pip install suite/auto-sync/
```

**Comment by VoltagedDebunked** [comment]
alright, ill try that.

thanks  a lot - that definetly helped.

**Comment by Rot127** [comment]
Nice! Let me know if I can be of any help.

I highly advice you to read the refactor guide as well: https://github.com/capstone-engine/capstone/blob/next/suite/auto-sync/RefactorGuide.md

It should give you a good intro about everything. And if you think something is not clear or missing, please let me know. So it can be improved.

You can also join our [Telegram community channel](https://t.me/CapstoneEngine) and ask questions there. Some more people with refactor experience are in there as well and might help quicker if I am unavailable. 

> use Python 3.13 it will be fixed with https://github.com/capstone-engine/capstone/pull/2705.

The PR is stuck on a bug in tree-sitter. I pinged the maintainers about it and hope they resolve it quickly. Otherwise will add a work-around. Sorry, super annoying that it doesn't work with Python 3.13 out of the box.

**Comment by VoltagedDebunked** [comment]
> Nice! Let me know if I can be of any help.
> 
> I highly advice you to read the refactor guide as well: https://github.com/capstone-engine/capstone/blob/next/suite/auto-sync/RefactorGuide.md...

alr, i will definetly do it, thanks a lot for the help - i will make sure to read it.

**Comment by VoltagedDebunked** [comment]
Yeah i think im gonna stick to manual, llvm tblgen wont work for me. The python stuff doesnt do either, i tried uv, maybe ill try again later.

**Comment by Rot127** [comment]
Can you please open an issue what is not working so we can fix it.

**Comment by VoltagedDebunked** [comment]
> Can you please open an issue what is not working so we can fix it.

of course! ill gather some quick info, and then i will post it on issues.

**Comment by VoltagedDebunked** [comment]
yeah i dont think its an actual issue i think its just me being autistic :sob:

**Comment by Rot127** [comment]
> yeah i dont think its an actual issue i think its just me being autistic 😭

If I can help somehow let me know.

We haven't decided internally yet if we can accept a manual PR.
Having AVR would be super awesome for sure! But the problem with mostly hand-written code is, that it is really hard to maintain. Especially since there is the option of using Auto-Sync.

Without it we can't cross check against LLVM, because the code base is not the same.
Also AVR might get extensions in the future. And having a semi-automated update mechanism for it just speeds things up a lot.

**Comment by VoltagedDebunked** [comment]
> > yeah i dont think its an actual issue i think its just me being autistic 😭
> 
> If I can help somehow let me know.
> 
> We haven't decided internall...

alright, ill try to tinker with it, and then try actual rewrite with the standard approach.

**Comment by VoltagedDebunked** [comment]
nevermind, i dont think it works for me. it breaks my system's llvm since im on arch linux, auto-sync had to be rewritten by me just for it to not clean immediately after generating the c++ stuff, had to reclone the same repo numerous times, and really - i dont mind maintaining avr, i mean - hppa is manually implemented, so why not this one? its a simple 8-bit microcontroller, i think using a whole toolchain with complex syncs will be overkill. if you can, ill polish anything else, but using llvm, i dont really think of. and havent really used llvm tooling (except for clang and its tools) before. thanks for understanding.

**Comment by notxvilka** [comment]
> nevermind, i dont think it works for me. it breaks my system's llvm since im on arch linux, auto-sync had to be rewritten by me just for it to not clean immediately after generating the c++ stuff, had to reclone the same repo numerous times, and really - i dont mind maintaining avr, i mean - hppa is manually implemented, so why not this one? its a simple 8-bit microcontroller, i think using a whole toolchain with complex syncs will be overkill. if you can, ill polish anything else, but using llvm, i dont really think of. and havent really used llvm tooling (except for clang and its tools) before. thanks for understanding.

HPPA is not in the mainstream LLVM. And for not breaking your system LLVM you can just use a docker container (or alternatives). Just my 2c.

**Comment by VoltagedDebunked** [comment]
> > nevermind, i dont think it works for me. it breaks my system's llvm since im on arch linux, auto-sync had to be rewritten by me just for it to not clean immdiately after generating the c++ stuff, had to reclone the same repo numerous times, and really - i dont mind maintaining avr, i mean - hppa is manually implemented, so why not this one? its a simple 8-bit microcontroller, i think using a whole toolchain with complex syncs will be overkill. if you can, ill polish anything else, but using llvm, i dont really think of. and havent really used llvm tooling (except for clang and its tools) before. thanks for understanding.
> 
> HPPA is not in the mainstream LLVM. And for not breaking your system LLVM you can just use a docker container (or alternatives). Just my 2c.

still, id honestly just try and make it manual, i dont mind maintaining it, i dont have anything better to do honestly

**Comment by Rot127** [comment]
> still, id honestly just try and make it manual, i dont mind maintaining it, i dont have anything better to do honestly

Feel free to go ahead. Having AVR is nice one way or the other. Please merge https://github.com/VoltagedDebunked/capstone/pull/1 so you have a good test coverage to work with.

**Comment by VoltagedDebunked** [comment]
Merged! thanks a lot for the help, ill test it now.

**Comment by VoltagedDebunked** [comment]
alright i tested it, looks good, pretty much, it works just fine and i disassembled a bunch of avr binaries, using my own program, i installed the library locally, and then i built a test program, and it integrates quite solidly, no segfaults, and pretty accurate disassembly. i think its really close to a merge.

**Comment by VoltagedDebunked** [comment]
alright, i got one major issue fixed:

Some encodings were incorrect. i fixed it by changing the register extraction.

also added support for X/Y/Z + instructions.

File: arch/AVR/AVRDecoder.c [hunk 1]
```diff
@@ -0,0 +1,575 @@
...
+    unsigned Rd = (insn >> 4) & 0x1F;
+    
+    MCOperand_CreateReg0(MI, AVR_REG_R0 + Rd);
+    
+    return MCDisassembler_Success;
+}
+
+static DecodeStatus DecodeBranch(MCInst *MI, uint16_t insn, uint64_t addr, const void *decoder)
+{
+    int16_t offset = (int16_t)(insn << 4) >> 4; // Sign extend 12-bit offset
```
Comment (Rot127) [inline arch/AVR/AVRDecoder.c]: Please implement a new helper function for sign extension in `MathExtras.h` like there already is for `SignExtend32`.

File: arch/AVR/AVRDecoder.c [hunk 2]
```diff
@@ -0,0 +1,575 @@
...
+    int64_t target = addr + (offset * 2) + 2;   // PC-relative, word-addressed
+    
+    MCOperand_CreateImm0(MI, target);
+    
+    return MCDisassembler_Success;
+}
+
+static DecodeStatus DecodeBranchSR(MCInst *MI, uint16_t insn, uint64_t addr, const void *decoder)
+{
+    int8_t offset = (int8_t)(insn << 1) >> 1;  // Sign extend 7-bit offset
```
Comment (Rot127) [inline arch/AVR/AVRDecoder.c]: Also please add a SignExtend function.

File: arch/AVR/AVRDecoder.c [hunk 3]
```diff
@@ -0,0 +1,575 @@
...
+        mode = 2;
+    } else if ((insn & 0x000F) == 0x0004) { // Z register for LPM
+        ptr = AVR_REG_Z;
+        mode = 0;
+    } else if ((insn & 0x000F) == 0x0005) { // Z+ register for LPM
+        ptr = AVR_REG_Z;
+        mode = 1;
+    } else {
+        return MCDisassembler_Fail;
+    }
```
Comment (Rot127) [inline arch/AVR/AVRDecoder.c]: Replace with a switch

File: arch/AVR/AVRDecoder.c [hunk 4]
```diff
@@ -0,0 +1,575 @@
...
+    MCOperand_CreateImm0(MI, K);
+    
+    return MCDisassembler_Success;
+}
+
+static DecodeStatus DecodeIndirect(MCInst *MI, uint16_t insn, uint64_t addr, const void *decoder)
+{
+    unsigned Rd = (insn >> 4) & 0x1F;
+    unsigned ptr = 0;
+    unsigned mode = 0; // 0=normal, 1=post-inc, 2=pre-dec
```
Comment (Rot127) [inline arch/AVR/AVRDecoder.c]: No magic numbers here please. Add an enum and use it for the mode.
Also the addressing mode should also be in the details, right?

File: arch/AVR/AVRDisassembler.c [hunk 5]
```diff
@@ -0,0 +1,158 @@
...
+#include "../../MCRegisterInfo.h"
+#include "../../MCDisassembler.h"
+#include "../../utils.h"
+#include "AVRDisassembler.h"
+#include "AVRMapping.h"
+
+#ifdef CAPSTONE_HAS_AVR
+
+// Register decoder helpers
+static unsigned __attribute__((unused)) DecodeGPR8RegisterClass(MCInst *Inst, unsigned RegNo,
```
Comment (Rot127) [inline arch/AVR/AVRDisassembler.c]:
```suggestion
static unsigned DecodeGPR8RegisterClass(MCInst *Inst, unsigned RegNo,
```

Also below. At lease before we merge it.

File: arch/AVR/AVRDisassembler.c [hunk 6]
```diff
@@ -0,0 +1,158 @@
...
+    MCOperand_CreateImm0(Inst, Imm);
+    return MCDisassembler_Success;
+}
+
+static unsigned __attribute__((unused)) DecodeRelativeImm7(MCInst *Inst, unsigned Imm,
+                                  uint64_t Address, const void *Decoder)
+{
+    // Sign extend 7-bit immediate
+    if (Imm & 0x40)
+        Imm |= 0xFFFFFF80;
```
Comment (Rot127) [inline arch/AVR/AVRDisassembler.c]: Use function as above.

File: arch/AVR/AVRDisassembler.c [hunk 7]
```diff
@@ -0,0 +1,158 @@
...
+    MCOperand_CreateImm0(Inst, Imm);
+    return MCDisassembler_Success;
+}
+
+static unsigned __attribute__((unused)) DecodeRelativeImm12(MCInst *Inst, unsigned Imm,
+                                   uint64_t Address, const void *Decoder)
+{
+    // Sign extend 12-bit immediate
+    if (Imm & 0x800)
+        Imm |= 0xFFFFF000;
```
Comment (Rot127) [inline arch/AVR/AVRDisassembler.c]: Into function please.

File: arch/AVR/AVRDisassembler.c [hunk 8]
```diff
@@ -0,0 +1,158 @@
...
+    
+    MCOperand_CreateImm0(Inst, Offset);
+    return MCDisassembler_Success;
+}
+
+// I/O register decoder
+static unsigned __attribute__((unused)) DecodeIORegister(MCInst *Inst, unsigned RegNo,
+                                uint64_t Address, const void *Decoder)
+{
+    if (RegNo > 63)
```
Comment (Rot127) [inline arch/AVR/AVRDisassembler.c]:
```suggestion
    if (RegNo >= AVR_REG_ENDING)
```

Also at the other places.

File: arch/AVR/AVRDisassembler.c [hunk 9]
```diff
@@ -0,0 +1,158 @@
...
+    }
+    
+    uint16_t Insn = (Bytes[1] << 8) | Bytes[0];
+    *Size = 2;
+    
+    // Check for 32-bit instructions (JMP, CALL, LDS, STS)
+    if ((Insn & 0xFE0E) == 0x940C || // JMP
+        (Insn & 0xFE0E) == 0x940E || // CALL
+        (Insn & 0xFE0F) == 0x9000 || // LDS
+        (Insn & 0xFE0F) == 0x9200) { // STS
```
Comment (Rot127) [inline arch/AVR/AVRDisassembler.c:39]: Use the function you defined above.

File: arch/AVR/AVRInstPrinter.c [hunk 10]
```diff
@@ -0,0 +1,197 @@
...
+    case AVR_REG_R30: return "r30";
+    case AVR_REG_R31: return "r31";
+    case AVR_REG_PC: return "PC";
+    case AVR_REG_SREG: return "SREG";
+    default: 
+        // Handle special cases for pointer registers
+        if (RegNo == AVR_REG_X) return "X";
+        if (RegNo == AVR_REG_Y) return "Y";
+        if (RegNo == AVR_REG_Z) return "Z";
+        if (RegNo == AVR_REG_SP) return "SP";
```
Comment (Rot127) [inline arch/AVR/AVRInstPrinter.c]: Make them case labels please

File: arch/AVR/AVRInstPrinter.c [hunk 11]
```diff
@@ -0,0 +1,197 @@
...
+    }
+}
+
+static void printRegName(SStream *O, unsigned RegNo)
+{
+    const char *name = getRegisterName(RegNo);
+    if (name) {
+        SStream_concat0(O, name);
+    } else {
+        SStream_concat(O, "UNKNOWN_REG_%u", RegNo);
```
Comment (Rot127) [inline arch/AVR/AVRInstPrinter.c]:
```suggestion
        SStream_concat(O, "UNKNOWN_REG_%" PRIu32, RegNo);
```

File: arch/AVR/AVRInstPrinter.c [hunk 12]
```diff
@@ -0,0 +1,197 @@
...
+    if (MCOperand_isReg(Op)) {
+        unsigned reg = MCOperand_getReg(Op);
+        printRegName(O, reg);
+    } else if (MCOperand_isImm(Op)) {
+        int64_t imm = MCOperand_getImm(Op);
+        if (imm >= 0 && imm <= 9)
+            SStream_concat(O, "%"PRId64, imm);
+        else
+            SStream_concat(O, "$0x%"PRIx64, (uint64_t)imm);
+    }
```
Comment (Rot127) [inline arch/AVR/AVRInstPrinter.c]: Use `PrintUInt` functions

File: arch/AVR/AVRInstPrinter.c [hunk 13]
```diff
@@ -0,0 +1,197 @@
...
+}
+
+static void __attribute__((unused)) printImmOperand(MCInst *MI, unsigned OpNo, SStream *O)
+{
+    MCOperand *Op = MCInst_getOperand(MI, OpNo);
+    
+    if (MCOperand_isImm(Op)) {
+        int64_t imm = MCOperand_getImm(Op);
+        SStream_concat(O, "0x%"PRIx64, (uint64_t)imm);
```
Comment (Rot127) [inline arch/AVR/AVRInstPrinter.c]: `printUInt`

File: arch/AVR/AVRInstPrinter.c [hunk 14]
```diff
@@ -0,0 +1,197 @@
...
+    MCOperand *Disp = MCInst_getOperand(MI, OpNo + 1);
+    
+    if (MCOperand_isReg(Base)) {
+        printRegName(O, MCOperand_getReg(Base));
+        if (MCOperand_isImm(Disp)) {
+            int64_t disp = MCOperand_getImm(Disp);
+            if (disp != 0) {
+                SStream_concat(O, "+%"PRId64, disp);
+            }
+        }
```
Comment (Rot127) [inline arch/AVR/AVRInstPrinter.c]: This code will never be reached. Because `MCOperand_isReg` was true.

Also please use `printUInt` functions

File: arch/AVR/AVRInstPrinter.c [hunk 15]
```diff
@@ -0,0 +1,197 @@
...
+    }
+}
+
+static void __attribute__((unused)) printIOOperand(MCInst *MI, unsigned OpNo, SStream *O)
+{
+    MCOperand *Op = MCInst_getOperand(MI, OpNo);
+    
+    if (MCOperand_isImm(Op)) {
+        int64_t addr = MCOperand_getImm(Op);
+        SStream_concat(O, "0x%02"PRIx64, (uint64_t)addr);
```
Comment (Rot127) [inline arch/AVR/AVRInstPrinter.c]: printuint

File: arch/AVR/AVRInstPrinter.c [hunk 16]
```diff
@@ -0,0 +1,197 @@
...
+static void __attribute__((unused)) printBranchOperand(MCInst *MI, unsigned OpNo, SStream *O)
+{
+    MCOperand *Op = MCInst_getOperand(MI, OpNo);
+    
+    if (MCOperand_isImm(Op)) {
+        int64_t offset = MCOperand_getImm(Op);
+        if (offset >= 0)
+            SStream_concat(O, ".+%"PRId64, offset * 2 + 2);
+        else
+            SStream_concat(O, ".%"PRId64, offset * 2 + 2);
```
Comment (Rot127) [inline arch/AVR/AVRInstPrinter.c]: printuint

File: arch/AVR/AVRInstPrinter.c [hunk 17]
```diff
@@ -0,0 +1,197 @@
...
+        for (unsigned i = 0; i < numOps; i++) {
+            if (i > 0) {
+                SStream_concat0(O, ", ");
+            }
+            printOperand(MI, i, O);
+        }
+    }
+    
+    // Set up instruction details for Capstone - with safety checks
+    if (MI->flat_insn && MI->flat_insn->detail) {
```
Comment (Rot127) [inline arch/AVR/AVRInstPrinter.c:105]: The `MI->flat_insn` check should be at the beginning of the function. But you can assume it is.
For the detail NULL check use `detail_is_set(MI)`. Also invert the condition and return early if detail is unset.

File: arch/AVR/AVRInstPrinter.c [hunk 18]
```diff
@@ -0,0 +1,197 @@
...
+        cs_avr *avr = &(MI->flat_insn->detail->avr);
```
Comment (Rot127) [inline arch/AVR/AVRInstPrinter.c:106]: Add a helper in `Mapping.h` to get the AVR details. See `DEFINE_get_arch_detail`

File: arch/AVR/AVRInstPrinter.c [hunk 19]
```diff
@@ -0,0 +1,197 @@
...
+        if (avr) {
```
Comment (Rot127) [inline arch/AVR/AVRInstPrinter.c]: This can be assumed.

File: arch/AVR/AVRInstPrinter.c [hunk 20]
```diff
@@ -0,0 +1,197 @@
...
+            avr->op_count = 0;
+            
+            // Fill in operand details
+            for (unsigned i = 0; i < numOps && i < 3 && avr->op_count < 3; i++) {
```
Comment (Rot127) [inline arch/AVR/AVRInstPrinter.c]: Replace `3` with a macro.

File: arch/AVR/AVRInstPrinter.c [hunk 21]
```diff
@@ -0,0 +1,197 @@
...
+                MCOperand *Op = MCInst_getOperand(MI, i);
+                if (Op) {
```
Comment (Rot127) [inline arch/AVR/AVRInstPrinter.c]: Invert condition.

File: arch/AVR/AVRInstPrinter.c [hunk 22]
```diff
@@ -0,0 +1,197 @@
...
+                    cs_avr_op *op = &avr->operands[avr->op_count];
```
Comment (Rot127) [inline arch/AVR/AVRInstPrinter.c]: Add helper with `DECL_get_detail_op` and use it here

File: arch/AVR/AVRInstPrinter.c [hunk 23]
```diff
@@ -0,0 +1,197 @@
...
+                    
+                    if (MCOperand_isReg(Op)) {
+                        op->type = AVR_OP_REG;
+                        op->reg = MCOperand_getReg(Op);
+                        avr->op_count++;
+                    } else if (MCOperand_isImm(Op)) {
+                        op->type = AVR_OP_IMM;
+                        op->imm = (int32_t)MCOperand_getImm(Op);
+                        avr->op_count++;
```
Comment (Rot127) [inline arch/AVR/AVRInstPrinter.c]: Add helper `DEFINE_inc_detail_op_count` and use it here.

File: arch/AVR/AVRInstPrinter.c [hunk 24]
```diff
@@ -0,0 +1,197 @@
...
+                    }
+                }
+            }
+            
+            // Add instruction groups - with safety check
+            if (PrinterInfo) {
+                AVR_get_insn_id((cs_struct *)PrinterInfo, MI->flat_insn, OpCode);
```
Comment (Rot127) [inline arch/AVR/AVRInstPrinter.c]: `(cs_struct *)PrinterInfo` is no valid cast. `PrinterInfo` is of type `MCRegisterInfo *`

File: arch/AVR/AVRMapping.c [hunk 25]
```diff
@@ -0,0 +1,559 @@
...
+    }
+    
+    const char *name = id2name(reg_name_maps, sizeof(reg_name_maps)/sizeof(reg_name_maps[0]), reg);
+    if (!name) {
+        // Debug: print what register ID we couldn't find
+        // You can remove this later
+        static char unknown_reg[32];
+        snprintf(unknown_reg, sizeof(unknown_reg), "REG_%u", reg);
+        return unknown_reg;
+    }
```
Comment (Rot127) [inline arch/AVR/AVRMapping.c:257]: It should just return NULL in that case. Because this leaks

File: arch/AVR/AVRInstPrinter.c (hunk 10 above)
Comment (Rot127) [reply arch/AVR/AVRInstPrinter.c]: Actually, please us the lookup function from AVRMapping.c
Otherwise we have duplicate code.

File: arch/AVR/AVRMapping.c [hunk 26]
```diff
@@ -0,0 +1,559 @@
...
+    { AVR_GRP_MCU_CONTROL, "mcu_control" },
+};
+
+const char *AVR_reg_name(csh handle, unsigned int reg)
+{
+    if (reg == 0 || reg >= AVR_REG_ENDING) {
+        return NULL;  // Invalid register ID
+    }
+    
+    const char *name = id2name(reg_name_maps, sizeof(reg_name_maps)/sizeof(reg_name_maps[0]), reg);
```
Comment (Rot127) [inline arch/AVR/AVRMapping.c]:
```suggestion
    const char *name = id2name(reg_name_maps, ARR_SIZE(reg_name_maps), reg);
```

File: arch/AVR/AVRMapping.c [hunk 27]
```diff
@@ -0,0 +1,559 @@
...
+        static char unknown_reg[32];
+        snprintf(unknown_reg, sizeof(unknown_reg), "REG_%u", reg);
+        return unknown_reg;
+    }
+    return name;
+}
+
+const char *AVR_insn_name(csh handle, unsigned int insn)
+{
+    return id2name(insn_name_maps, sizeof(insn_name_maps)/sizeof(insn_name_maps[0]), insn);
```
Comment (Rot127) [inline arch/AVR/AVRMapping.c]: ARR_SIZE

File: arch/AVR/AVRMapping.c [hunk 28]
```diff
@@ -0,0 +1,559 @@
...
+}
+
+const char *AVR_group_name(csh handle, unsigned int group)
+{
+    return id2name(group_name_maps, sizeof(group_name_maps)/sizeof(group_name_maps[0]), group);
```
Comment (Rot127) [inline arch/AVR/AVRMapping.c]: ARR_SIZE

File: arch/AVR/AVRMapping.c [hunk 29]
```diff
@@ -0,0 +1,559 @@
...
+        return;
+    }
+    
+    // Set instruction groups based on the instruction type
+    switch (id) {
+    case AVR_INS_RJMP:
+    case AVR_INS_IJMP:
+    case AVR_INS_EIJMP:
+    case AVR_INS_JMP:
+        if (insn->detail->groups_count < 8) {
```
Comment (Rot127) [inline arch/AVR/AVRMapping.c]: No magic numbers please. Move the 8 into a macro def

File: arch/AVR/AVRMapping.c [hunk 30]
```diff
@@ -0,0 +1,559 @@
...
+    // Set instruction ID
+    insn->id = id;
+    
+    // Safety check for detail structure
+    if (!insn->detail) {
+        return;
+    }
+    
+    // Set instruction groups based on the instruction type
+    switch (id) {
```
Comment (Rot127) [inline arch/AVR/AVRMapping.c:282]: THe groups should be added earlier. Not in `AVR_get_insn_id`.

I would actually recomment to leave this function empty and just set everything in `AVR_printInstr`

File: arch/AVR/AVRModule.c [hunk 31]
```diff
@@ -0,0 +1,135 @@
...
+    26, 28, 30, // X, Y, Z
+    31, 32, 33  // SP, PC, SREG
+};
+
+cs_err AVR_global_init(cs_struct *ud)
+{
+    MCRegisterInfo *mri;
+    mri = cs_mem_malloc(sizeof(*mri));
+    
+    MCRegisterInfo_InitMCRegisterInfo(mri, AVRRegDesc, sizeof(AVRRegDesc)/sizeof(AVRRegDesc[0]),
```
Comment (Rot127) [inline arch/AVR/AVRModule.c:105]: It seems like you don't use this profile. You can remove it, or am I missing something?

File: cstool/cstool.c
Comment (Rot127) [inline cstool/cstool.c:1]: Revert the formatting changes please.

File: cstool/cstool_aarch64.c
Comment (Rot127) [inline cstool/cstool_aarch64.c:1]: revert

Comment (Rot127) [reply cstool/cstool_aarch64.c:1]: Also for all the others.

File: cstool/cstool_avr.c [hunk 32]
```diff
@@ -0,0 +1,65 @@
...
+
+	if (ins->detail == NULL)
+		return;
+
+	avr = &(ins->detail->avr);
+
+	if (avr->op_count)
+		printf("\top_count: %u\n", avr->op_count);
+
+	for (i = 0; i < avr->op_count; i++) {
```
Comment (Rot127) [inline cstool/cstool_avr.c:20]: Define `i` in the loop.

File: cstool/cstool_avr.c [hunk 33]
```diff
@@ -0,0 +1,65 @@
...
+			printf("\t\toperands[%d].type: INVALID\n", i);
+			break;
+
+		case AVR_OP_REG:
+			printf("\t\toperands[%d].type: REG = %s\n", i,
+			       cs_reg_name(handle, op->reg));
+			break;
+
+		case AVR_OP_IMM:
+			printf("\t\toperands[%d].type: IMM = 0x%x (%d)\n", i,
```
Comment (Rot127) [inline cstool/cstool_avr.c:33]: Use the `PRI` macros please

File: cstool/cstool_avr.c [hunk 34]
```diff
@@ -0,0 +1,65 @@
...
+			printf("\t\toperands[%d].type: MEM\n", i);
+			printf("\t\t\tbase register: %s\n",
+			       cs_reg_name(handle, op->mem.base));
+			printf("\t\t\tdisplacement: %d\n", op->mem.disp);
+			break;
+		}
+	}
+
+	// Print registers read/written by instruction
+	if (!cs_regs_access(handle, ins, regs_read, &regs_read_count,
```
Comment (Rot127) [inline cstool/cstool_avr.c:47]: Compare to `CS_ERR_OK` please

File: include/capstone/avr.h [hunk 35]
```diff
@@ -0,0 +1,231 @@
...
+
+#ifdef __cplusplus
+extern "C" {
+#endif
+
+#include "platform.h"
+
+#ifdef _MSC_VER
+#pragma warning(disable:4201)
+#pragma warning(disable:4214)
```
Comment (Rot127) [inline include/capstone/avr.h]:
```suggestion
```

File: include/capstone/avr.h [hunk 36]
```diff
@@ -0,0 +1,231 @@
...
+    AVR_GRP_JUMP,     // All jump instructions
+    AVR_GRP_CALL,     // All call instructions 
+    AVR_GRP_RET,      // All return instructions
+    AVR_GRP_INT,      // All interrupt instructions
+    AVR_GRP_IRET,     // All interrupt return instructions
+    AVR_GRP_PRIVILEGE,// All privileged instructions
+    AVR_GRP_BRANCH_RELATIVE, // All relative branching instructions
+    
+    // Architecture-specific groups
+    AVR_GRP_ARITHMETIC,   // Arithmetic operations
```
Comment (Rot127) [inline include/capstone/avr.h]:
```suggestion
    AVR_GRP_ARITHMETIC = 128,   // Arithmetic operations
```

File: include/capstone/avr.h [hunk 37]
```diff
@@ -0,0 +1,231 @@
...
+    
+    AVR_INS_ENDING
+} avr_insn;
+
+// AVR operand types
+typedef enum avr_op_type {
+    AVR_OP_INVALID = 0, // Uninitialized/invalid operand
+    AVR_OP_REG,         // Register operand
+    AVR_OP_IMM,         // Immediate operand
+    AVR_OP_MEM,         // Memory operand
```
Comment (Rot127) [inline include/capstone/avr.h]:
```suggestion
    AVR_OP_INVALID = CS_OP_INVALID, // Uninitialized/invalid operand
    AVR_OP_REG = CS_OP_REG,         // Register operand
    AVR_OP_IMM = CS_OP_IMM,         // Immediate operand
    AVR_OP_MEM = CS_OP_MEM,         // Memory operand
```

You need to include `cs_operand.h`

File: include/capstone/avr.h [hunk 38]
```diff
@@ -0,0 +1,231 @@
...
+        avr_reg reg;    // Register value for REG operand
+        int32_t imm;    // Immediate value for IMM operand
+        avr_op_mem mem; // Memory operand
+    };
+} cs_avr_op;
+
+// Instruction structure in AVR-specific format
+typedef struct cs_avr {
+    uint8_t op_count;   // Number of operands
+    cs_avr_op operands[3]; // Up to 3 operands per instruction
```
Comment (Rot127) [inline include/capstone/avr.h:223]: Move the `3` into a macro def

File: tests/MC/AVR/inst_adc_avr.txt.yaml [hunk 39]
```diff
@@ -0,0 +1,40 @@
+test_cases:
+  -
+    input:
+      bytes: [ 0x0f, 0x1c ]
+      arch: "CS_ARCH_AVR"
+      options: [ "avr" ]
```
Comment (Rot127) [inline tests/MC/AVR/inst_adc_avr.txt.yaml:6]: You can keep the options empty.

File: tests/MC/AVR/inst_adc_avr.txt.yaml [hunk 40]
```diff
@@ -0,0 +1,40 @@
+test_cases:
+  -
+    input:
+      bytes: [ 0x0f, 0x1c ]
+      arch: "CS_ARCH_AVR"
```
Comment (Rot127) [inline tests/MC/AVR/inst_adc_avr.txt.yaml:5]: `CS_ARCH_AVR` must be added to `test_mapping.h`. Don't forget to sort the table!

**Review by Rot127 — CHANGES_REQUESTED** [review]
Thanks a lot for all the work!

Please make the tests run (see https://github.com/capstone-engine/capstone/pull/2726#discussion_r2133968195) and fix failing ones, and don't forget to add the fuzzing tests from https://github.com/VoltagedDebunked/capstone/pull/2 please

**Comment by VoltagedDebunked** [comment]
alright i will

**Comment by VoltagedDebunked** [comment]
[ 75%] Building C object CMakeFiles/capstone.dir/arch/AVR/AVRInstPrinter.c.o
[ 76%] Building C object CMakeFiles/capstone.dir/arch/AVR/AVRDecoder.c.o
/home/voltaged/Projects/capstone-test/arch/AVR/AVRDisassembler.c:23:17: error: ‘DecodeGPR8RegisterClass’ defined but not used [-Werror=unused-function]
   23 | static unsigned DecodeGPR8RegisterClass(MCInst *Inst, unsigned RegNo,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/capstone.dir/build.make:1549: CMakeFiles/capstone.dir/arch/AVR/AVRDisassembler.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:97: CMakeFiles/capstone.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

i need to add __attribute__((unused)) to resolve the error.

**Comment by VoltagedDebunked** [comment]
same for the other branch, io, and other functions.

**Comment by Rot127** [comment]
> i need to add attribute((unused)) to resolve the error.

Can't you just remove the function? Or comment it out until it is needed? In either case, for developing it is fine if they are still there. Just in the final version there shouldn't be anything unused.

**Comment by VoltagedDebunked** [comment]
oh, sure! ill do that.

**Comment by VoltagedDebunked** [comment]
Done! Tested, too

**Comment by Rot127** [comment]
> Done! Tested, too

The CI is red though. Please fix it.

**Comment by VoltagedDebunked** [comment]
alright

**Comment by VoltagedDebunked** [comment]
can you launch the CI please? so i can see if its fixed

**Comment by VoltagedDebunked** [comment]
are u serious vro i cant even view it cuz it cuts off cuz my wifi so bad are you serious bruh

**Comment by notxvilka** [comment]
> are u serious vro i cant even view it cuz it cuts off cuz my wifi so bad are you serious bruh

A useful hack - you can download log archives, just press the "gear" icon in the top right corner and choose "Download log archives", e.g. in your case it would be https://github.com/capstone-engine/capstone/suites/39790166017/logs?attempt=2
Then you can check them locally without any hassle.

**Comment by VoltagedDebunked** [comment]
thanks!

**Comment by VoltagedDebunked** [comment]
closed this pull request for now. im sorry, i just cant get it right. maybe ill come back later.

**Comment by Rot127** [comment]
Ok, feel free to continue it whenever you find time.
